/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'net.atview.richtext.facet'

export { $nsid }

/** Annotation of a sub-string within the parent record's `textContent`. Byte offsets refer to a UTF-8 encoding of the string. A single facet may carry multiple features that all apply to the same byte range. */
type Main = {
  $type?: 'net.atview.richtext.facet'
  index: ByteSlice
  features: (
    | l.$Typed<B>
    | l.$Typed<I>
    | l.$Typed<U>
    | l.$Typed<Code>
    | l.$Typed<Strikethrough>
    | l.$Typed<Highlight>
    | l.$Typed<Link>
    | l.$Typed<Mention>
    | l.$Typed<H2>
    | l.$Typed<H3>
    | l.$Typed<H4>
    | l.$Typed<H5>
    | l.$Typed<H6>
    | l.$Typed<Blockquote>
    | l.$Typed<CodeBlock>
    | l.$Typed<Media>
    | l.$Typed<BskyPost>
    | l.$Typed<Ul>
    | l.$Typed<Ol>
    | l.$Typed<Website>
    | l.$Typed<HorizontalRule>
    | l.$Typed<Iframe>
    | l.$Typed<Math>
    | l.$Typed<HardBreak>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

/** Annotation of a sub-string within the parent record's `textContent`. Byte offsets refer to a UTF-8 encoding of the string. A single facet may carry multiple features that all apply to the same byte range. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    index: l.ref<ByteSlice>((() => byteSlice) as any),
    features: l.array(
      l.typedUnion(
        [
          l.typedRef<B>((() => b) as any),
          l.typedRef<I>((() => i) as any),
          l.typedRef<U>((() => u) as any),
          l.typedRef<Code>((() => code) as any),
          l.typedRef<Strikethrough>((() => strikethrough) as any),
          l.typedRef<Highlight>((() => highlight) as any),
          l.typedRef<Link>((() => link) as any),
          l.typedRef<Mention>((() => mention) as any),
          l.typedRef<H2>((() => h2) as any),
          l.typedRef<H3>((() => h3) as any),
          l.typedRef<H4>((() => h4) as any),
          l.typedRef<H5>((() => h5) as any),
          l.typedRef<H6>((() => h6) as any),
          l.typedRef<Blockquote>((() => blockquote) as any),
          l.typedRef<CodeBlock>((() => codeBlock) as any),
          l.typedRef<Media>((() => media) as any),
          l.typedRef<BskyPost>((() => bskyPost) as any),
          l.typedRef<Ul>((() => ul) as any),
          l.typedRef<Ol>((() => ol) as any),
          l.typedRef<Website>((() => website) as any),
          l.typedRef<HorizontalRule>((() => horizontalRule) as any),
          l.typedRef<Iframe>((() => iframe) as any),
          l.typedRef<Math>((() => math) as any),
          l.typedRef<HardBreak>((() => hardBreak) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are in UTF-8 bytes. */
type ByteSlice = {
  $type?: 'net.atview.richtext.facet#byteSlice'
  byteStart: number
  byteEnd: number
}

export type { ByteSlice }

/** Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are in UTF-8 bytes. */
const byteSlice = l.typedObject<ByteSlice>(
  $nsid,
  'byteSlice',
  l.object({
    byteStart: l.integer({ minimum: 0 }),
    byteEnd: l.integer({ minimum: 0 }),
  }),
)

export { byteSlice }

/** Width/height ratio of an image, in arbitrary same-unit pixels. */
type AspectRatio = {
  $type?: 'net.atview.richtext.facet#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

/** Width/height ratio of an image, in arbitrary same-unit pixels. */
const aspectRatio = l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  l.object({
    width: l.integer({ minimum: 1 }),
    height: l.integer({ minimum: 1 }),
  }),
)

export { aspectRatio }

/** Bold inline emphasis. */
type B = { $type?: 'net.atview.richtext.facet#b' }

export type { B }

/** Bold inline emphasis. */
const b = l.typedObject<B>($nsid, 'b', l.object({}))

export { b }

/** Italic inline emphasis. */
type I = { $type?: 'net.atview.richtext.facet#i' }

export type { I }

/** Italic inline emphasis. */
const i = l.typedObject<I>($nsid, 'i', l.object({}))

export { i }

/** Underline inline emphasis. */
type U = { $type?: 'net.atview.richtext.facet#u' }

export type { U }

/** Underline inline emphasis. */
const u = l.typedObject<U>($nsid, 'u', l.object({}))

export { u }

/** Inline monospace / code span. */
type Code = { $type?: 'net.atview.richtext.facet#code' }

export type { Code }

/** Inline monospace / code span. */
const code = l.typedObject<Code>($nsid, 'code', l.object({}))

export { code }

/** Strikethrough inline emphasis. */
type Strikethrough = { $type?: 'net.atview.richtext.facet#strikethrough' }

export type { Strikethrough }

/** Strikethrough inline emphasis. */
const strikethrough = l.typedObject<Strikethrough>(
  $nsid,
  'strikethrough',
  l.object({}),
)

export { strikethrough }

/** Highlighted inline emphasis. */
type Highlight = { $type?: 'net.atview.richtext.facet#highlight' }

export type { Highlight }

/** Highlighted inline emphasis. */
const highlight = l.typedObject<Highlight>($nsid, 'highlight', l.object({}))

export { highlight }

/** Hyperlink inline feature. */
type Link = { $type?: 'net.atview.richtext.facet#link'; uri: l.UriString }

export type { Link }

/** Hyperlink inline feature. */
const link = l.typedObject<Link>(
  $nsid,
  'link',
  l.object({ uri: l.string({ format: 'uri' }) }),
)

export { link }

/** Mention of an account by DID. */
type Mention = { $type?: 'net.atview.richtext.facet#mention'; did: l.DidString }

export type { Mention }

/** Mention of an account by DID. */
const mention = l.typedObject<Mention>(
  $nsid,
  'mention',
  l.object({ did: l.string({ format: 'did' }) }),
)

export { mention }

/** Level 2 heading block. */
type H2 = { $type?: 'net.atview.richtext.facet#h2' }

export type { H2 }

/** Level 2 heading block. */
const h2 = l.typedObject<H2>($nsid, 'h2', l.object({}))

export { h2 }

/** Level 3 heading block. */
type H3 = { $type?: 'net.atview.richtext.facet#h3' }

export type { H3 }

/** Level 3 heading block. */
const h3 = l.typedObject<H3>($nsid, 'h3', l.object({}))

export { h3 }

/** Level 4 heading block. */
type H4 = { $type?: 'net.atview.richtext.facet#h4' }

export type { H4 }

/** Level 4 heading block. */
const h4 = l.typedObject<H4>($nsid, 'h4', l.object({}))

export { h4 }

/** Level 5 heading block. */
type H5 = { $type?: 'net.atview.richtext.facet#h5' }

export type { H5 }

/** Level 5 heading block. */
const h5 = l.typedObject<H5>($nsid, 'h5', l.object({}))

export { h5 }

/** Level 6 heading block. */
type H6 = { $type?: 'net.atview.richtext.facet#h6' }

export type { H6 }

/** Level 6 heading block. */
const h6 = l.typedObject<H6>($nsid, 'h6', l.object({}))

export { h6 }

/** Blockquote block. */
type Blockquote = { $type?: 'net.atview.richtext.facet#blockquote' }

export type { Blockquote }

/** Blockquote block. */
const blockquote = l.typedObject<Blockquote>($nsid, 'blockquote', l.object({}))

export { blockquote }

/** Fenced code block with optional language hint. */
type CodeBlock = {
  $type?: 'net.atview.richtext.facet#codeBlock'
  language?: string
}

export type { CodeBlock }

/** Fenced code block with optional language hint. */
const codeBlock = l.typedObject<CodeBlock>(
  $nsid,
  'codeBlock',
  l.object({ language: l.optional(l.string({ maxLength: 100 })) }),
)

export { codeBlock }

/** Inline/embedded media (image) with optional metadata. */
type Media = {
  $type?: 'net.atview.richtext.facet#media'
  image: l.BlobRef
  aspectRatio?: AspectRatio
  altText?: string
  caption?: string
  title?: string
}

export type { Media }

/** Inline/embedded media (image) with optional metadata. */
const media = l.typedObject<Media>(
  $nsid,
  'media',
  l.object({
    image: l.blob({ accept: ['image/*'], maxSize: 5000000 }),
    aspectRatio: l.optional(l.ref<AspectRatio>((() => aspectRatio) as any)),
    altText: l.optional(l.string({ maxLength: 10000, maxGraphemes: 1000 })),
    caption: l.optional(l.string({ maxLength: 10000, maxGraphemes: 1000 })),
    title: l.optional(l.string({ maxLength: 5000, maxGraphemes: 500 })),
  }),
)

export { media }

/** Embedded reference to a Bluesky post (app.bsky.feed.post). */
type BskyPost = {
  $type?: 'net.atview.richtext.facet#bskyPost'
  uri: l.AtUriString
  cid?: l.CidString
}

export type { BskyPost }

/** Embedded reference to a Bluesky post (app.bsky.feed.post). */
const bskyPost = l.typedObject<BskyPost>(
  $nsid,
  'bskyPost',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
  }),
)

export { bskyPost }

/** Unordered list item block. */
type Ul = { $type?: 'net.atview.richtext.facet#ul' }

export type { Ul }

/** Unordered list item block. */
const ul = l.typedObject<Ul>($nsid, 'ul', l.object({}))

export { ul }

/** Ordered list item block. */
type Ol = { $type?: 'net.atview.richtext.facet#ol' }

export type { Ol }

/** Ordered list item block. */
const ol = l.typedObject<Ol>($nsid, 'ol', l.object({}))

export { ol }

/** External website embed. */
type Website = {
  $type?: 'net.atview.richtext.facet#website'
  uri: l.UriString
  title?: string
}

export type { Website }

/** External website embed. */
const website = l.typedObject<Website>(
  $nsid,
  'website',
  l.object({
    uri: l.string({ format: 'uri' }),
    title: l.optional(l.string({ maxLength: 5000, maxGraphemes: 500 })),
  }),
)

export { website }

/** Horizontal rule / thematic break block. */
type HorizontalRule = { $type?: 'net.atview.richtext.facet#horizontalRule' }

export type { HorizontalRule }

/** Horizontal rule / thematic break block. */
const horizontalRule = l.typedObject<HorizontalRule>(
  $nsid,
  'horizontalRule',
  l.object({}),
)

export { horizontalRule }

/** Embedded iframe block. */
type Iframe = {
  $type?: 'net.atview.richtext.facet#iframe'
  url: l.UriString
  height?: number
}

export type { Iframe }

/** Embedded iframe block. */
const iframe = l.typedObject<Iframe>(
  $nsid,
  'iframe',
  l.object({
    url: l.string({ format: 'uri' }),
    height: l.optional(l.integer({ minimum: 1 })),
  }),
)

export { iframe }

/** Math block expressed as TeX source. */
type Math = { $type?: 'net.atview.richtext.facet#math'; tex: string }

export type { Math }

/** Math block expressed as TeX source. */
const math = l.typedObject<Math>(
  $nsid,
  'math',
  l.object({ tex: l.string({ maxLength: 100000 }) }),
)

export { math }

/** Hard line break within a paragraph. */
type HardBreak = { $type?: 'net.atview.richtext.facet#hardBreak' }

export type { HardBreak }

/** Hard line break within a paragraph. */
const hardBreak = l.typedObject<HardBreak>($nsid, 'hardBreak', l.object({}))

export { hardBreak }
