/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RichtextFacet from './richtext\\facet.defs.js'

const $nsid = 'net.atview.document'

export { $nsid }

/** Atview content payload. Slots into the `content` open union of a site.standard.document record. Provides a compact, stream-friendly representation of rich text as a plain `textContent` string paired with an array of byte-indexed facets. */
type Main = {
  $type?: 'net.atview.document'

  /**
   * Rich-text facets marking byte ranges of the parent record's `textContent` with inline and block-level features.
   */
  facets?: RichtextFacet.Main[]

  /**
   * Alt text for the parent record's `coverImage` blob.
   */
  coverImageAlt?: string

  /**
   * BCP-47 language tag describing the primary language of `textContent` (e.g. `en`, `en-US`).
   */
  language?: string
}

export type { Main }

/** Atview content payload. Slots into the `content` open union of a site.standard.document record. Provides a compact, stream-friendly representation of rich text as a plain `textContent` string paired with an array of byte-indexed facets. */
const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    facets: l.optional(
      l.array(l.ref<RichtextFacet.Main>((() => RichtextFacet.main) as any)),
    ),
    coverImageAlt: l.optional(l.string({ maxLength: 5000, maxGraphemes: 500 })),
    language: l.optional(l.string({ maxLength: 32 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
